const newsCountries = [
	{ countryName: "Argentina", countryCode: "ar" },
	{ countryName: "Australia", countryCode: "au" },
	{ countryName: "Austria", countryCode: "at" },
	{ countryName: "Belgium", countryCode: "be" },
	{ countryName: "Brazil", countryCode: "br" },
	{ countryName: "Bulgaria", countryCode: "bg" },
	{ countryName: "Canada", countryCode: "ca" },
	{ countryName: "China", countryCode: "cn" },
	{ countryName: "Columbia", countryCode: "co" },
	{ countryName: "Cuba", countryCode: "cu" },
	{ countryName: "Czech Republic", countryCode: "cz" },
	{ countryName: "Egypt", countryCode: "eg" },
	{ countryName: "France", countryCode: "fr" },
	{ countryName: "Germany", countryCode: "de" },
	{ countryName: "Greece", countryCode: "gr" },
	{ countryName: "Hong Kong", countryCode: "hk" },
	{ countryName: "Hungary", countryCode: "hu" },
	{ countryName: "India", countryCode: "in" },
	{ countryName: "Indonesia", countryCode: "id" },
	{ countryName: "Ireland", countryCode: "ie" },
	{ countryName: "Israel", countryCode: "il" },
	{ countryName: "Italy", countryCode: "it" },
	{ countryName: "Japan", countryCode: "jp" },
	{ countryName: "Latvia", countryCode: "lv" },
	{ countryName: "Lithuania", countryCode: "lt" },
	{ countryName: "Malaysia", countryCode: "my" },
	{ countryName: "Mexico", countryCode: "mx" },
	{ countryName: "Morocco", countryCode: "ma" },
	{ countryName: "Netherlands", countryCode: "nl" },
	{ countryName: "New Zealand", countryCode: "nz" },
	{ countryName: "Nigeria", countryCode: "ng" },
	{ countryName: "Norway", countryCode: "no" },
	{ countryName: "Philippines", countryCode: "ph" },
	{ countryName: "Poland", countryCode: "pl" },
	{ countryName: "Portugal", countryCode: "pt" },
	{ countryName: "Romania", countryCode: "ro" },
	{ countryName: "Russia", countryCode: "ru" },
	{ countryName: "Saudi Arabia", countryCode: "sa" },
	{ countryName: "Serbia", countryCode: "rs" },
	{ countryName: "Singapore", countryCode: "sg" },
	{ countryName: "Slovakia", countryCode: "sk" },
	{ countryName: "Slovenia", countryCode: "si" },
	{ countryName: "South Africa", countryCode: "za" },
	{ countryName: "South Korea", countryCode: "kr" },
	{ countryName: "Sweden", countryCode: "se" },
	{ countryName: "Switzerland", countryCode: "ch" },
	{ countryName: "Taiwan", countryCode: "tw" },
	{ countryName: "Thailand", countryCode: "th" },
	{ countryName: "Turkey", countryCode: "tr" },
	{ countryName: "UAE", countryCode: "ae" },
	{ countryName: "Ukraine", countryCode: "ua" },
	{ countryName: "United Kingdom", countryCode: "gb" },
	{ countryName: "United States", countryCode: "us" },
	{ countryName: "Venuzuela", countryCode: "ve" },
];

export default newsCountries;
